# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivar Larsson
email: ivar@larsson.me
description: > # this means to ignore newlines until "baseurl:"
  ops and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.larsson.me" # the base hostname & protocol for your site
twitter_username: ivarmedi
github_username:  ivarmedi

# Build settings
markdown: kramdown
